# Generated by Django 5.2.16 on 2026-09-26 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_alter_profile_institute_alter_profile_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('desc', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In_Progress', 'In Progress'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('team_size', models.PositiveBigIntegerField(default=1)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images')),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('required_skills', models.ManyToManyField(related_name='projects', to='accounts.skill')),
            ],
        ),
    ]
