# Generated by Django 5.2.16 on 2026-09-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='overview',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
