# Generated by Django 5.2.16 on 2026-10-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='compensation_type',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Negotiable', 'Negotiable')], default='Unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_amount',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
