# Generated by Django 5.2.16 on 2026-10-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_joinrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='payment_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='JoinRequest',
        ),
    ]
