# Generated by Django 5.2.16 on 2026-09-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='user',
            field=models.ManyToManyField(to='accounts.profile'),
        ),
    ]
