# Generated by Django 5.2.16 on 2026-09-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_skills_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(to='accounts.skills'),
        ),
    ]
