# Generated by Django 5.2.16 on 2026-09-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='institute',
            field=models.CharField(blank=True, default='Independent', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='Remote', max_length=100, null=True),
        ),
    ]
