# Generated by Django 5.2.16 on 2026-10-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_no',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
