# Generated by Django 5.2.16 on 2026-10-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/static/images/default.svg', null=True, upload_to='images'),
        ),
    ]
